set -g history-limit 20000
set -g mouse on
set -g detach-on-destroy off
set -g destroy-unattached off
set -s exit-unattached off
setw -g remain-on-exit on
setw -g automatic-rename off
set -g status-right 'Biohub | %Y-%m-%d %H:%M'
